# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from offboard_control/Status.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Status(genpy.Message):
  _md5sum = "a0c7abb5783c6834587efbd77de4a4a3"
  _type = "offboard_control/Status"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string state
geometry_msgs/Pose uav1_position
geometry_msgs/Quaternion uav1_orientation
geometry_msgs/Pose uav2_position
geometry_msgs/Quaternion uav2_orientation
================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['state','uav1_position','uav1_orientation','uav2_position','uav2_orientation']
  _slot_types = ['string','geometry_msgs/Pose','geometry_msgs/Quaternion','geometry_msgs/Pose','geometry_msgs/Quaternion']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       state,uav1_position,uav1_orientation,uav2_position,uav2_orientation

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Status, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.state is None:
        self.state = ''
      if self.uav1_position is None:
        self.uav1_position = geometry_msgs.msg.Pose()
      if self.uav1_orientation is None:
        self.uav1_orientation = geometry_msgs.msg.Quaternion()
      if self.uav2_position is None:
        self.uav2_position = geometry_msgs.msg.Pose()
      if self.uav2_orientation is None:
        self.uav2_orientation = geometry_msgs.msg.Quaternion()
    else:
      self.state = ''
      self.uav1_position = geometry_msgs.msg.Pose()
      self.uav1_orientation = geometry_msgs.msg.Quaternion()
      self.uav2_position = geometry_msgs.msg.Pose()
      self.uav2_orientation = geometry_msgs.msg.Quaternion()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_22d().pack(_x.uav1_position.position.x, _x.uav1_position.position.y, _x.uav1_position.position.z, _x.uav1_position.orientation.x, _x.uav1_position.orientation.y, _x.uav1_position.orientation.z, _x.uav1_position.orientation.w, _x.uav1_orientation.x, _x.uav1_orientation.y, _x.uav1_orientation.z, _x.uav1_orientation.w, _x.uav2_position.position.x, _x.uav2_position.position.y, _x.uav2_position.position.z, _x.uav2_position.orientation.x, _x.uav2_position.orientation.y, _x.uav2_position.orientation.z, _x.uav2_position.orientation.w, _x.uav2_orientation.x, _x.uav2_orientation.y, _x.uav2_orientation.z, _x.uav2_orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.uav1_position is None:
        self.uav1_position = geometry_msgs.msg.Pose()
      if self.uav1_orientation is None:
        self.uav1_orientation = geometry_msgs.msg.Quaternion()
      if self.uav2_position is None:
        self.uav2_position = geometry_msgs.msg.Pose()
      if self.uav2_orientation is None:
        self.uav2_orientation = geometry_msgs.msg.Quaternion()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.state = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.state = str[start:end]
      _x = self
      start = end
      end += 176
      (_x.uav1_position.position.x, _x.uav1_position.position.y, _x.uav1_position.position.z, _x.uav1_position.orientation.x, _x.uav1_position.orientation.y, _x.uav1_position.orientation.z, _x.uav1_position.orientation.w, _x.uav1_orientation.x, _x.uav1_orientation.y, _x.uav1_orientation.z, _x.uav1_orientation.w, _x.uav2_position.position.x, _x.uav2_position.position.y, _x.uav2_position.position.z, _x.uav2_position.orientation.x, _x.uav2_position.orientation.y, _x.uav2_position.orientation.z, _x.uav2_position.orientation.w, _x.uav2_orientation.x, _x.uav2_orientation.y, _x.uav2_orientation.z, _x.uav2_orientation.w,) = _get_struct_22d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_22d().pack(_x.uav1_position.position.x, _x.uav1_position.position.y, _x.uav1_position.position.z, _x.uav1_position.orientation.x, _x.uav1_position.orientation.y, _x.uav1_position.orientation.z, _x.uav1_position.orientation.w, _x.uav1_orientation.x, _x.uav1_orientation.y, _x.uav1_orientation.z, _x.uav1_orientation.w, _x.uav2_position.position.x, _x.uav2_position.position.y, _x.uav2_position.position.z, _x.uav2_position.orientation.x, _x.uav2_position.orientation.y, _x.uav2_position.orientation.z, _x.uav2_position.orientation.w, _x.uav2_orientation.x, _x.uav2_orientation.y, _x.uav2_orientation.z, _x.uav2_orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.uav1_position is None:
        self.uav1_position = geometry_msgs.msg.Pose()
      if self.uav1_orientation is None:
        self.uav1_orientation = geometry_msgs.msg.Quaternion()
      if self.uav2_position is None:
        self.uav2_position = geometry_msgs.msg.Pose()
      if self.uav2_orientation is None:
        self.uav2_orientation = geometry_msgs.msg.Quaternion()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.state = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.state = str[start:end]
      _x = self
      start = end
      end += 176
      (_x.uav1_position.position.x, _x.uav1_position.position.y, _x.uav1_position.position.z, _x.uav1_position.orientation.x, _x.uav1_position.orientation.y, _x.uav1_position.orientation.z, _x.uav1_position.orientation.w, _x.uav1_orientation.x, _x.uav1_orientation.y, _x.uav1_orientation.z, _x.uav1_orientation.w, _x.uav2_position.position.x, _x.uav2_position.position.y, _x.uav2_position.position.z, _x.uav2_position.orientation.x, _x.uav2_position.orientation.y, _x.uav2_position.orientation.z, _x.uav2_position.orientation.w, _x.uav2_orientation.x, _x.uav2_orientation.y, _x.uav2_orientation.z, _x.uav2_orientation.w,) = _get_struct_22d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_22d = None
def _get_struct_22d():
    global _struct_22d
    if _struct_22d is None:
        _struct_22d = struct.Struct("<22d")
    return _struct_22d
