takeoff_points:
  uav1:
    position_x: 0.0
    position_y: 0.0
    position_z: 1.0
    orientation_x: 0.0
    orientation_y: 0.0
    orientation_z: 0.0
    orientation_w: 1.0
  uav2:
    position_x: 0.0
    position_y: 0.0
    position_z: 2.0
    orientation_x: 0.0
    orientation_y: 0.0
    orientation_z: 0.0
    orientation_w: 1.0
size:
  claw:
    diameter: 0.3
  rope:
    length: 1.0
  up_cable:
    high: 1.0
position:
  onLinePoint_Z: 1.0
  targetPointError1: 0.1
  targetPointError2: 0.3
  satbleVelError1: 0.05
descend:
  height: {first: 0.5, second: 0.2, third: 0.1}
sensor_install:
  error_x: 0.0
  error_y: 0.0
  error_z: 0.0
sensor_range:
  range_z: 700.0 # mm