takeoff_points:
  uav1:
    position_x: 0.0
    position_y: 0.0
    position_z: 1.0
    orientation_x: 0.0
    orientation_y: 0.0
    orientation_z: 0.0
    orientation_w: 1.0
  uav2:
    position_x: 0.0
    position_y: 0.0
    position_z: 2.0
    orientation_x: 0.0
    orientation_y: 0.0
    orientation_z: 0.0
    orientation_w: 1.0
online_points:
  cable_point:
    position_x: 3.0
    position_y: 3.0
    position_z: 3.0
    orientation_x: 0.0
    orientation_y: 0.0
    orientation_z: 0.0
    orientation_w: 1.0
size:
  claw:
    diameter: 0.3
  rope:
    length: 1.0
  up_cable:
    high: 1.0
home_points:
  uav1:
    position_x: 0.0
    position_y: 0.0
    position_z: 0.1
    orientation_x: 0.0
    orientation_y: 0.0
    orientation_z: 0.0
    orientation_w: 0.0
  uav2:
    position_x: 0.0
    position_y: 1.0
    position_z: 0.1
    orientation_x: 0.0
    orientation_y: 0.0
    orientation_z: 0.0
    orientation_w: 0.0