waypoints_set_1:
  - position: {x: 0.0, y: 3.0, z: 3.0}
    orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
  - position: {x: 1.0, y: 3.0, z: 3.0}
    orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
  - position: {x: 2.0, y: 3.0, z: 3.0}
    orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
  - position: {x: 3.0, y: 3.0, z: 3.0}
    orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
  - position: {x: 4.0, y: 3.0, z: 3.0}
    orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}

waypoints_set_2:
  - position: {x: 5.0, y: 3.0, z: 3.0}
    orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
  - position: {x: 6.0, y: 3.0, z: 3.0}
    orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
  - position: {x: 7.0, y: 3.0, z: 3.0}
    orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
  - position: {x: 8.0, y: 3.0, z: 3.0}
    orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
  - position: {x: 9.0, y: 3.0, z: 3.0}
    orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}