// Generated by gencpp from file offboard_control/GenTrajOnline.msg
// DO NOT EDIT!


#ifndef OFFBOARD_CONTROL_MESSAGE_GENTRAJONLINE_H
#define OFFBOARD_CONTROL_MESSAGE_GENTRAJONLINE_H

#include <ros/service_traits.h>


#include <offboard_control/GenTrajOnlineRequest.h>
#include <offboard_control/GenTrajOnlineResponse.h>


namespace offboard_control
{

struct GenTrajOnline
{

typedef GenTrajOnlineRequest Request;
typedef GenTrajOnlineResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GenTrajOnline
} // namespace offboard_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::offboard_control::GenTrajOnline > {
  static const char* value()
  {
    return "1c8daf56fea4f669979846d8a40908f8";
  }

  static const char* value(const ::offboard_control::GenTrajOnline&) { return value(); }
};

template<>
struct DataType< ::offboard_control::GenTrajOnline > {
  static const char* value()
  {
    return "offboard_control/GenTrajOnline";
  }

  static const char* value(const ::offboard_control::GenTrajOnline&) { return value(); }
};


// service_traits::MD5Sum< ::offboard_control::GenTrajOnlineRequest> should match
// service_traits::MD5Sum< ::offboard_control::GenTrajOnline >
template<>
struct MD5Sum< ::offboard_control::GenTrajOnlineRequest>
{
  static const char* value()
  {
    return MD5Sum< ::offboard_control::GenTrajOnline >::value();
  }
  static const char* value(const ::offboard_control::GenTrajOnlineRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::offboard_control::GenTrajOnlineRequest> should match
// service_traits::DataType< ::offboard_control::GenTrajOnline >
template<>
struct DataType< ::offboard_control::GenTrajOnlineRequest>
{
  static const char* value()
  {
    return DataType< ::offboard_control::GenTrajOnline >::value();
  }
  static const char* value(const ::offboard_control::GenTrajOnlineRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::offboard_control::GenTrajOnlineResponse> should match
// service_traits::MD5Sum< ::offboard_control::GenTrajOnline >
template<>
struct MD5Sum< ::offboard_control::GenTrajOnlineResponse>
{
  static const char* value()
  {
    return MD5Sum< ::offboard_control::GenTrajOnline >::value();
  }
  static const char* value(const ::offboard_control::GenTrajOnlineResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::offboard_control::GenTrajOnlineResponse> should match
// service_traits::DataType< ::offboard_control::GenTrajOnline >
template<>
struct DataType< ::offboard_control::GenTrajOnlineResponse>
{
  static const char* value()
  {
    return DataType< ::offboard_control::GenTrajOnline >::value();
  }
  static const char* value(const ::offboard_control::GenTrajOnlineResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OFFBOARD_CONTROL_MESSAGE_GENTRAJONLINE_H
