// Generated by gencpp from file offboard_control/isUavArrivedRequest.msg
// DO NOT EDIT!


#ifndef OFFBOARD_CONTROL_MESSAGE_ISUAVARRIVEDREQUEST_H
#define OFFBOARD_CONTROL_MESSAGE_ISUAVARRIVEDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace offboard_control
{
template <class ContainerAllocator>
struct isUavArrivedRequest_
{
  typedef isUavArrivedRequest_<ContainerAllocator> Type;

  isUavArrivedRequest_()
    : targetPoint()
    , uavID(0)  {
    }
  isUavArrivedRequest_(const ContainerAllocator& _alloc)
    : targetPoint(_alloc)
    , uavID(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _targetPoint_type;
  _targetPoint_type targetPoint;

   typedef uint8_t _uavID_type;
  _uavID_type uavID;





  typedef boost::shared_ptr< ::offboard_control::isUavArrivedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::offboard_control::isUavArrivedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct isUavArrivedRequest_

typedef ::offboard_control::isUavArrivedRequest_<std::allocator<void> > isUavArrivedRequest;

typedef boost::shared_ptr< ::offboard_control::isUavArrivedRequest > isUavArrivedRequestPtr;
typedef boost::shared_ptr< ::offboard_control::isUavArrivedRequest const> isUavArrivedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::offboard_control::isUavArrivedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::offboard_control::isUavArrivedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::offboard_control::isUavArrivedRequest_<ContainerAllocator1> & lhs, const ::offboard_control::isUavArrivedRequest_<ContainerAllocator2> & rhs)
{
  return lhs.targetPoint == rhs.targetPoint &&
    lhs.uavID == rhs.uavID;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::offboard_control::isUavArrivedRequest_<ContainerAllocator1> & lhs, const ::offboard_control::isUavArrivedRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace offboard_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::offboard_control::isUavArrivedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::offboard_control::isUavArrivedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offboard_control::isUavArrivedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offboard_control::isUavArrivedRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offboard_control::isUavArrivedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offboard_control::isUavArrivedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::offboard_control::isUavArrivedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe78b9b615816ee275f9bae3c27a36c6";
  }

  static const char* value(const ::offboard_control::isUavArrivedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe78b9b615816ee2ULL;
  static const uint64_t static_value2 = 0x75f9bae3c27a36c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::offboard_control::isUavArrivedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "offboard_control/isUavArrivedRequest";
  }

  static const char* value(const ::offboard_control::isUavArrivedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::offboard_control::isUavArrivedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped targetPoint\n"
"uint8 uavID\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::offboard_control::isUavArrivedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::offboard_control::isUavArrivedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.targetPoint);
      stream.next(m.uavID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct isUavArrivedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::offboard_control::isUavArrivedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::offboard_control::isUavArrivedRequest_<ContainerAllocator>& v)
  {
    s << indent << "targetPoint: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.targetPoint);
    s << indent << "uavID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.uavID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OFFBOARD_CONTROL_MESSAGE_ISUAVARRIVEDREQUEST_H
