// Generated by gencpp from file offboard_control/isUavArrived.msg
// DO NOT EDIT!


#ifndef OFFBOARD_CONTROL_MESSAGE_ISUAVARRIVED_H
#define OFFBOARD_CONTROL_MESSAGE_ISUAVARRIVED_H

#include <ros/service_traits.h>


#include <offboard_control/isUavArrivedRequest.h>
#include <offboard_control/isUavArrivedResponse.h>


namespace offboard_control
{

struct isUavArrived
{

typedef isUavArrivedRequest Request;
typedef isUavArrivedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct isUavArrived
} // namespace offboard_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::offboard_control::isUavArrived > {
  static const char* value()
  {
    return "753b28f691163b5366ad20e7061a9439";
  }

  static const char* value(const ::offboard_control::isUavArrived&) { return value(); }
};

template<>
struct DataType< ::offboard_control::isUavArrived > {
  static const char* value()
  {
    return "offboard_control/isUavArrived";
  }

  static const char* value(const ::offboard_control::isUavArrived&) { return value(); }
};


// service_traits::MD5Sum< ::offboard_control::isUavArrivedRequest> should match
// service_traits::MD5Sum< ::offboard_control::isUavArrived >
template<>
struct MD5Sum< ::offboard_control::isUavArrivedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::offboard_control::isUavArrived >::value();
  }
  static const char* value(const ::offboard_control::isUavArrivedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::offboard_control::isUavArrivedRequest> should match
// service_traits::DataType< ::offboard_control::isUavArrived >
template<>
struct DataType< ::offboard_control::isUavArrivedRequest>
{
  static const char* value()
  {
    return DataType< ::offboard_control::isUavArrived >::value();
  }
  static const char* value(const ::offboard_control::isUavArrivedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::offboard_control::isUavArrivedResponse> should match
// service_traits::MD5Sum< ::offboard_control::isUavArrived >
template<>
struct MD5Sum< ::offboard_control::isUavArrivedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::offboard_control::isUavArrived >::value();
  }
  static const char* value(const ::offboard_control::isUavArrivedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::offboard_control::isUavArrivedResponse> should match
// service_traits::DataType< ::offboard_control::isUavArrived >
template<>
struct DataType< ::offboard_control::isUavArrivedResponse>
{
  static const char* value()
  {
    return DataType< ::offboard_control::isUavArrived >::value();
  }
  static const char* value(const ::offboard_control::isUavArrivedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OFFBOARD_CONTROL_MESSAGE_ISUAVARRIVED_H
