// Generated by gencpp from file offboard_control/isUavArrivedResponse.msg
// DO NOT EDIT!


#ifndef OFFBOARD_CONTROL_MESSAGE_ISUAVARRIVEDRESPONSE_H
#define OFFBOARD_CONTROL_MESSAGE_ISUAVARRIVEDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace offboard_control
{
template <class ContainerAllocator>
struct isUavArrivedResponse_
{
  typedef isUavArrivedResponse_<ContainerAllocator> Type;

  isUavArrivedResponse_()
    : isArrived(false)  {
    }
  isUavArrivedResponse_(const ContainerAllocator& _alloc)
    : isArrived(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isArrived_type;
  _isArrived_type isArrived;





  typedef boost::shared_ptr< ::offboard_control::isUavArrivedResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::offboard_control::isUavArrivedResponse_<ContainerAllocator> const> ConstPtr;

}; // struct isUavArrivedResponse_

typedef ::offboard_control::isUavArrivedResponse_<std::allocator<void> > isUavArrivedResponse;

typedef boost::shared_ptr< ::offboard_control::isUavArrivedResponse > isUavArrivedResponsePtr;
typedef boost::shared_ptr< ::offboard_control::isUavArrivedResponse const> isUavArrivedResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::offboard_control::isUavArrivedResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::offboard_control::isUavArrivedResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::offboard_control::isUavArrivedResponse_<ContainerAllocator1> & lhs, const ::offboard_control::isUavArrivedResponse_<ContainerAllocator2> & rhs)
{
  return lhs.isArrived == rhs.isArrived;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::offboard_control::isUavArrivedResponse_<ContainerAllocator1> & lhs, const ::offboard_control::isUavArrivedResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace offboard_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::offboard_control::isUavArrivedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::offboard_control::isUavArrivedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offboard_control::isUavArrivedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offboard_control::isUavArrivedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offboard_control::isUavArrivedResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offboard_control::isUavArrivedResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::offboard_control::isUavArrivedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88de213cbe7d52dbd07f813d1b12f40a";
  }

  static const char* value(const ::offboard_control::isUavArrivedResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88de213cbe7d52dbULL;
  static const uint64_t static_value2 = 0xd07f813d1b12f40aULL;
};

template<class ContainerAllocator>
struct DataType< ::offboard_control::isUavArrivedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "offboard_control/isUavArrivedResponse";
  }

  static const char* value(const ::offboard_control::isUavArrivedResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::offboard_control::isUavArrivedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isArrived\n"
;
  }

  static const char* value(const ::offboard_control::isUavArrivedResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::offboard_control::isUavArrivedResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isArrived);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct isUavArrivedResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::offboard_control::isUavArrivedResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::offboard_control::isUavArrivedResponse_<ContainerAllocator>& v)
  {
    s << indent << "isArrived: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isArrived);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OFFBOARD_CONTROL_MESSAGE_ISUAVARRIVEDRESPONSE_H
