// Generated by gencpp from file offboard_control/Measure.msg
// DO NOT EDIT!


#ifndef OFFBOARD_CONTROL_MESSAGE_MEASURE_H
#define OFFBOARD_CONTROL_MESSAGE_MEASURE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace offboard_control
{
template <class ContainerAllocator>
struct Measure_
{
  typedef Measure_<ContainerAllocator> Type;

  Measure_()
    : is_valid(false)
    , x(0.0)
    , z(0.0)  {
    }
  Measure_(const ContainerAllocator& _alloc)
    : is_valid(false)
    , x(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _is_valid_type;
  _is_valid_type is_valid;

   typedef double _x_type;
  _x_type x;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::offboard_control::Measure_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::offboard_control::Measure_<ContainerAllocator> const> ConstPtr;

}; // struct Measure_

typedef ::offboard_control::Measure_<std::allocator<void> > Measure;

typedef boost::shared_ptr< ::offboard_control::Measure > MeasurePtr;
typedef boost::shared_ptr< ::offboard_control::Measure const> MeasureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::offboard_control::Measure_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::offboard_control::Measure_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::offboard_control::Measure_<ContainerAllocator1> & lhs, const ::offboard_control::Measure_<ContainerAllocator2> & rhs)
{
  return lhs.is_valid == rhs.is_valid &&
    lhs.x == rhs.x &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::offboard_control::Measure_<ContainerAllocator1> & lhs, const ::offboard_control::Measure_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace offboard_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::offboard_control::Measure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::offboard_control::Measure_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offboard_control::Measure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offboard_control::Measure_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offboard_control::Measure_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offboard_control::Measure_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::offboard_control::Measure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "038007aa6658d27492f7f0c6eeb28f91";
  }

  static const char* value(const ::offboard_control::Measure_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x038007aa6658d274ULL;
  static const uint64_t static_value2 = 0x92f7f0c6eeb28f91ULL;
};

template<class ContainerAllocator>
struct DataType< ::offboard_control::Measure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "offboard_control/Measure";
  }

  static const char* value(const ::offboard_control::Measure_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::offboard_control::Measure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_valid\n"
"float64 x\n"
"float64 z\n"
;
  }

  static const char* value(const ::offboard_control::Measure_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::offboard_control::Measure_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_valid);
      stream.next(m.x);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Measure_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::offboard_control::Measure_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::offboard_control::Measure_<ContainerAllocator>& v)
  {
    s << indent << "is_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_valid);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OFFBOARD_CONTROL_MESSAGE_MEASURE_H
