// Generated by gencpp from file offboard_control/SetOffboardCtlType.msg
// DO NOT EDIT!


#ifndef OFFBOARD_CONTROL_MESSAGE_SETOFFBOARDCTLTYPE_H
#define OFFBOARD_CONTROL_MESSAGE_SETOFFBOARDCTLTYPE_H

#include <ros/service_traits.h>


#include <offboard_control/SetOffboardCtlTypeRequest.h>
#include <offboard_control/SetOffboardCtlTypeResponse.h>


namespace offboard_control
{

struct SetOffboardCtlType
{

typedef SetOffboardCtlTypeRequest Request;
typedef SetOffboardCtlTypeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetOffboardCtlType
} // namespace offboard_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::offboard_control::SetOffboardCtlType > {
  static const char* value()
  {
    return "37b0bbed7a7478a029b22247760de72a";
  }

  static const char* value(const ::offboard_control::SetOffboardCtlType&) { return value(); }
};

template<>
struct DataType< ::offboard_control::SetOffboardCtlType > {
  static const char* value()
  {
    return "offboard_control/SetOffboardCtlType";
  }

  static const char* value(const ::offboard_control::SetOffboardCtlType&) { return value(); }
};


// service_traits::MD5Sum< ::offboard_control::SetOffboardCtlTypeRequest> should match
// service_traits::MD5Sum< ::offboard_control::SetOffboardCtlType >
template<>
struct MD5Sum< ::offboard_control::SetOffboardCtlTypeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::offboard_control::SetOffboardCtlType >::value();
  }
  static const char* value(const ::offboard_control::SetOffboardCtlTypeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::offboard_control::SetOffboardCtlTypeRequest> should match
// service_traits::DataType< ::offboard_control::SetOffboardCtlType >
template<>
struct DataType< ::offboard_control::SetOffboardCtlTypeRequest>
{
  static const char* value()
  {
    return DataType< ::offboard_control::SetOffboardCtlType >::value();
  }
  static const char* value(const ::offboard_control::SetOffboardCtlTypeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::offboard_control::SetOffboardCtlTypeResponse> should match
// service_traits::MD5Sum< ::offboard_control::SetOffboardCtlType >
template<>
struct MD5Sum< ::offboard_control::SetOffboardCtlTypeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::offboard_control::SetOffboardCtlType >::value();
  }
  static const char* value(const ::offboard_control::SetOffboardCtlTypeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::offboard_control::SetOffboardCtlTypeResponse> should match
// service_traits::DataType< ::offboard_control::SetOffboardCtlType >
template<>
struct DataType< ::offboard_control::SetOffboardCtlTypeResponse>
{
  static const char* value()
  {
    return DataType< ::offboard_control::SetOffboardCtlType >::value();
  }
  static const char* value(const ::offboard_control::SetOffboardCtlTypeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OFFBOARD_CONTROL_MESSAGE_SETOFFBOARDCTLTYPE_H
