// Generated by gencpp from file offboard_control/SetPidGains.msg
// DO NOT EDIT!


#ifndef OFFBOARD_CONTROL_MESSAGE_SETPIDGAINS_H
#define OFFBOARD_CONTROL_MESSAGE_SETPIDGAINS_H

#include <ros/service_traits.h>


#include <offboard_control/SetPidGainsRequest.h>
#include <offboard_control/SetPidGainsResponse.h>


namespace offboard_control
{

struct SetPidGains
{

typedef SetPidGainsRequest Request;
typedef SetPidGainsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPidGains
} // namespace offboard_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::offboard_control::SetPidGains > {
  static const char* value()
  {
    return "d57e186547bf189d8db08127479743cd";
  }

  static const char* value(const ::offboard_control::SetPidGains&) { return value(); }
};

template<>
struct DataType< ::offboard_control::SetPidGains > {
  static const char* value()
  {
    return "offboard_control/SetPidGains";
  }

  static const char* value(const ::offboard_control::SetPidGains&) { return value(); }
};


// service_traits::MD5Sum< ::offboard_control::SetPidGainsRequest> should match
// service_traits::MD5Sum< ::offboard_control::SetPidGains >
template<>
struct MD5Sum< ::offboard_control::SetPidGainsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::offboard_control::SetPidGains >::value();
  }
  static const char* value(const ::offboard_control::SetPidGainsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::offboard_control::SetPidGainsRequest> should match
// service_traits::DataType< ::offboard_control::SetPidGains >
template<>
struct DataType< ::offboard_control::SetPidGainsRequest>
{
  static const char* value()
  {
    return DataType< ::offboard_control::SetPidGains >::value();
  }
  static const char* value(const ::offboard_control::SetPidGainsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::offboard_control::SetPidGainsResponse> should match
// service_traits::MD5Sum< ::offboard_control::SetPidGains >
template<>
struct MD5Sum< ::offboard_control::SetPidGainsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::offboard_control::SetPidGains >::value();
  }
  static const char* value(const ::offboard_control::SetPidGainsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::offboard_control::SetPidGainsResponse> should match
// service_traits::DataType< ::offboard_control::SetPidGains >
template<>
struct DataType< ::offboard_control::SetPidGainsResponse>
{
  static const char* value()
  {
    return DataType< ::offboard_control::SetPidGains >::value();
  }
  static const char* value(const ::offboard_control::SetPidGainsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OFFBOARD_CONTROL_MESSAGE_SETPIDGAINS_H
