// Generated by gencpp from file offboard_control/SetTargetPoint.msg
// DO NOT EDIT!


#ifndef OFFBOARD_CONTROL_MESSAGE_SETTARGETPOINT_H
#define OFFBOARD_CONTROL_MESSAGE_SETTARGETPOINT_H

#include <ros/service_traits.h>


#include <offboard_control/SetTargetPointRequest.h>
#include <offboard_control/SetTargetPointResponse.h>


namespace offboard_control
{

struct SetTargetPoint
{

typedef SetTargetPointRequest Request;
typedef SetTargetPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTargetPoint
} // namespace offboard_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::offboard_control::SetTargetPoint > {
  static const char* value()
  {
    return "9a658aee9c9634e4e1d337a3edbe9137";
  }

  static const char* value(const ::offboard_control::SetTargetPoint&) { return value(); }
};

template<>
struct DataType< ::offboard_control::SetTargetPoint > {
  static const char* value()
  {
    return "offboard_control/SetTargetPoint";
  }

  static const char* value(const ::offboard_control::SetTargetPoint&) { return value(); }
};


// service_traits::MD5Sum< ::offboard_control::SetTargetPointRequest> should match
// service_traits::MD5Sum< ::offboard_control::SetTargetPoint >
template<>
struct MD5Sum< ::offboard_control::SetTargetPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::offboard_control::SetTargetPoint >::value();
  }
  static const char* value(const ::offboard_control::SetTargetPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::offboard_control::SetTargetPointRequest> should match
// service_traits::DataType< ::offboard_control::SetTargetPoint >
template<>
struct DataType< ::offboard_control::SetTargetPointRequest>
{
  static const char* value()
  {
    return DataType< ::offboard_control::SetTargetPoint >::value();
  }
  static const char* value(const ::offboard_control::SetTargetPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::offboard_control::SetTargetPointResponse> should match
// service_traits::MD5Sum< ::offboard_control::SetTargetPoint >
template<>
struct MD5Sum< ::offboard_control::SetTargetPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::offboard_control::SetTargetPoint >::value();
  }
  static const char* value(const ::offboard_control::SetTargetPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::offboard_control::SetTargetPointResponse> should match
// service_traits::DataType< ::offboard_control::SetTargetPoint >
template<>
struct DataType< ::offboard_control::SetTargetPointResponse>
{
  static const char* value()
  {
    return DataType< ::offboard_control::SetTargetPoint >::value();
  }
  static const char* value(const ::offboard_control::SetTargetPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OFFBOARD_CONTROL_MESSAGE_SETTARGETPOINT_H
