// Generated by gencpp from file offboard_control/SetUavTakeoffReadyResponse.msg
// DO NOT EDIT!


#ifndef OFFBOARD_CONTROL_MESSAGE_SETUAVTAKEOFFREADYRESPONSE_H
#define OFFBOARD_CONTROL_MESSAGE_SETUAVTAKEOFFREADYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace offboard_control
{
template <class ContainerAllocator>
struct SetUavTakeoffReadyResponse_
{
  typedef SetUavTakeoffReadyResponse_<ContainerAllocator> Type;

  SetUavTakeoffReadyResponse_()
    : offboard_enabled(false)
    , armed(false)  {
    }
  SetUavTakeoffReadyResponse_(const ContainerAllocator& _alloc)
    : offboard_enabled(false)
    , armed(false)  {
  (void)_alloc;
    }



   typedef uint8_t _offboard_enabled_type;
  _offboard_enabled_type offboard_enabled;

   typedef uint8_t _armed_type;
  _armed_type armed;





  typedef boost::shared_ptr< ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetUavTakeoffReadyResponse_

typedef ::offboard_control::SetUavTakeoffReadyResponse_<std::allocator<void> > SetUavTakeoffReadyResponse;

typedef boost::shared_ptr< ::offboard_control::SetUavTakeoffReadyResponse > SetUavTakeoffReadyResponsePtr;
typedef boost::shared_ptr< ::offboard_control::SetUavTakeoffReadyResponse const> SetUavTakeoffReadyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator1> & lhs, const ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator2> & rhs)
{
  return lhs.offboard_enabled == rhs.offboard_enabled &&
    lhs.armed == rhs.armed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator1> & lhs, const ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace offboard_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358fed19915ac0f7266841f0ce120de4";
  }

  static const char* value(const ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358fed19915ac0f7ULL;
  static const uint64_t static_value2 = 0x266841f0ce120de4ULL;
};

template<class ContainerAllocator>
struct DataType< ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "offboard_control/SetUavTakeoffReadyResponse";
  }

  static const char* value(const ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool offboard_enabled\n"
"bool armed\n"
;
  }

  static const char* value(const ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.offboard_enabled);
      stream.next(m.armed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetUavTakeoffReadyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::offboard_control::SetUavTakeoffReadyResponse_<ContainerAllocator>& v)
  {
    s << indent << "offboard_enabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.offboard_enabled);
    s << indent << "armed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.armed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OFFBOARD_CONTROL_MESSAGE_SETUAVTAKEOFFREADYRESPONSE_H
