// Generated by gencpp from file offboard_control/SetUavTakeoffReady.msg
// DO NOT EDIT!


#ifndef OFFBOARD_CONTROL_MESSAGE_SETUAVTAKEOFFREADY_H
#define OFFBOARD_CONTROL_MESSAGE_SETUAVTAKEOFFREADY_H

#include <ros/service_traits.h>


#include <offboard_control/SetUavTakeoffReadyRequest.h>
#include <offboard_control/SetUavTakeoffReadyResponse.h>


namespace offboard_control
{

struct SetUavTakeoffReady
{

typedef SetUavTakeoffReadyRequest Request;
typedef SetUavTakeoffReadyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetUavTakeoffReady
} // namespace offboard_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::offboard_control::SetUavTakeoffReady > {
  static const char* value()
  {
    return "bfb94ba5582dfe70c8390e8d16832c2a";
  }

  static const char* value(const ::offboard_control::SetUavTakeoffReady&) { return value(); }
};

template<>
struct DataType< ::offboard_control::SetUavTakeoffReady > {
  static const char* value()
  {
    return "offboard_control/SetUavTakeoffReady";
  }

  static const char* value(const ::offboard_control::SetUavTakeoffReady&) { return value(); }
};


// service_traits::MD5Sum< ::offboard_control::SetUavTakeoffReadyRequest> should match
// service_traits::MD5Sum< ::offboard_control::SetUavTakeoffReady >
template<>
struct MD5Sum< ::offboard_control::SetUavTakeoffReadyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::offboard_control::SetUavTakeoffReady >::value();
  }
  static const char* value(const ::offboard_control::SetUavTakeoffReadyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::offboard_control::SetUavTakeoffReadyRequest> should match
// service_traits::DataType< ::offboard_control::SetUavTakeoffReady >
template<>
struct DataType< ::offboard_control::SetUavTakeoffReadyRequest>
{
  static const char* value()
  {
    return DataType< ::offboard_control::SetUavTakeoffReady >::value();
  }
  static const char* value(const ::offboard_control::SetUavTakeoffReadyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::offboard_control::SetUavTakeoffReadyResponse> should match
// service_traits::MD5Sum< ::offboard_control::SetUavTakeoffReady >
template<>
struct MD5Sum< ::offboard_control::SetUavTakeoffReadyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::offboard_control::SetUavTakeoffReady >::value();
  }
  static const char* value(const ::offboard_control::SetUavTakeoffReadyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::offboard_control::SetUavTakeoffReadyResponse> should match
// service_traits::DataType< ::offboard_control::SetUavTakeoffReady >
template<>
struct DataType< ::offboard_control::SetUavTakeoffReadyResponse>
{
  static const char* value()
  {
    return DataType< ::offboard_control::SetUavTakeoffReady >::value();
  }
  static const char* value(const ::offboard_control::SetUavTakeoffReadyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OFFBOARD_CONTROL_MESSAGE_SETUAVTAKEOFFREADY_H
