// Generated by gencpp from file offboard_control/SetUavTakeoffReadyRequest.msg
// DO NOT EDIT!


#ifndef OFFBOARD_CONTROL_MESSAGE_SETUAVTAKEOFFREADYREQUEST_H
#define OFFBOARD_CONTROL_MESSAGE_SETUAVTAKEOFFREADYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace offboard_control
{
template <class ContainerAllocator>
struct SetUavTakeoffReadyRequest_
{
  typedef SetUavTakeoffReadyRequest_<ContainerAllocator> Type;

  SetUavTakeoffReadyRequest_()
    : uavID(0)  {
    }
  SetUavTakeoffReadyRequest_(const ContainerAllocator& _alloc)
    : uavID(0)  {
  (void)_alloc;
    }



   typedef uint8_t _uavID_type;
  _uavID_type uavID;





  typedef boost::shared_ptr< ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetUavTakeoffReadyRequest_

typedef ::offboard_control::SetUavTakeoffReadyRequest_<std::allocator<void> > SetUavTakeoffReadyRequest;

typedef boost::shared_ptr< ::offboard_control::SetUavTakeoffReadyRequest > SetUavTakeoffReadyRequestPtr;
typedef boost::shared_ptr< ::offboard_control::SetUavTakeoffReadyRequest const> SetUavTakeoffReadyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator1> & lhs, const ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator2> & rhs)
{
  return lhs.uavID == rhs.uavID;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator1> & lhs, const ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace offboard_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69ae467ce8ff6cb85ca62e798d7a5406";
  }

  static const char* value(const ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69ae467ce8ff6cb8ULL;
  static const uint64_t static_value2 = 0x5ca62e798d7a5406ULL;
};

template<class ContainerAllocator>
struct DataType< ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "offboard_control/SetUavTakeoffReadyRequest";
  }

  static const char* value(const ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 uavID\n"
;
  }

  static const char* value(const ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.uavID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetUavTakeoffReadyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::offboard_control::SetUavTakeoffReadyRequest_<ContainerAllocator>& v)
  {
    s << indent << "uavID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.uavID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OFFBOARD_CONTROL_MESSAGE_SETUAVTAKEOFFREADYREQUEST_H
