// Generated by gencpp from file offboard_control/StateControl.msg
// DO NOT EDIT!


#ifndef OFFBOARD_CONTROL_MESSAGE_STATECONTROL_H
#define OFFBOARD_CONTROL_MESSAGE_STATECONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace offboard_control
{
template <class ContainerAllocator>
struct StateControl_
{
  typedef StateControl_<ContainerAllocator> Type;

  StateControl_()
    : state_ctrl_type(0)  {
    }
  StateControl_(const ContainerAllocator& _alloc)
    : state_ctrl_type(0)  {
  (void)_alloc;
    }



   typedef uint8_t _state_ctrl_type_type;
  _state_ctrl_type_type state_ctrl_type;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(TAKEOFF)
  #undef TAKEOFF
#endif
#if defined(_WIN32) && defined(ARRIVE_ONLINE_POINT)
  #undef ARRIVE_ONLINE_POINT
#endif
#if defined(_WIN32) && defined(AJUST_ATTITUDE)
  #undef AJUST_ATTITUDE
#endif
#if defined(_WIN32) && defined(ON_LINE)
  #undef ON_LINE
#endif
#if defined(_WIN32) && defined(FOLLOW_CABLE)
  #undef FOLLOW_CABLE
#endif
#if defined(_WIN32) && defined(APPROACH_NODE)
  #undef APPROACH_NODE
#endif
#if defined(_WIN32) && defined(CROSS_NODE)
  #undef CROSS_NODE
#endif
#if defined(_WIN32) && defined(LAND)
  #undef LAND
#endif

  enum {
    TAKEOFF = 0u,
    ARRIVE_ONLINE_POINT = 1u,
    AJUST_ATTITUDE = 2u,
    ON_LINE = 3u,
    FOLLOW_CABLE = 4u,
    APPROACH_NODE = 5u,
    CROSS_NODE = 6u,
    LAND = 7u,
  };


  typedef boost::shared_ptr< ::offboard_control::StateControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::offboard_control::StateControl_<ContainerAllocator> const> ConstPtr;

}; // struct StateControl_

typedef ::offboard_control::StateControl_<std::allocator<void> > StateControl;

typedef boost::shared_ptr< ::offboard_control::StateControl > StateControlPtr;
typedef boost::shared_ptr< ::offboard_control::StateControl const> StateControlConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::offboard_control::StateControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::offboard_control::StateControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::offboard_control::StateControl_<ContainerAllocator1> & lhs, const ::offboard_control::StateControl_<ContainerAllocator2> & rhs)
{
  return lhs.state_ctrl_type == rhs.state_ctrl_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::offboard_control::StateControl_<ContainerAllocator1> & lhs, const ::offboard_control::StateControl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace offboard_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::offboard_control::StateControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::offboard_control::StateControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offboard_control::StateControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offboard_control::StateControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offboard_control::StateControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offboard_control::StateControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::offboard_control::StateControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32bbda18dc61a12eea4cc4f9975ef333";
  }

  static const char* value(const ::offboard_control::StateControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32bbda18dc61a12eULL;
  static const uint64_t static_value2 = 0xea4cc4f9975ef333ULL;
};

template<class ContainerAllocator>
struct DataType< ::offboard_control::StateControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "offboard_control/StateControl";
  }

  static const char* value(const ::offboard_control::StateControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::offboard_control::StateControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 state_ctrl_type\n"
"uint8 TAKEOFF = 0\n"
"uint8 ARRIVE_ONLINE_POINT = 1\n"
"uint8 AJUST_ATTITUDE = 2\n"
"uint8 ON_LINE = 3\n"
"uint8 FOLLOW_CABLE = 4\n"
"uint8 APPROACH_NODE = 5\n"
"uint8 CROSS_NODE = 6\n"
"uint8 LAND = 7\n"
;
  }

  static const char* value(const ::offboard_control::StateControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::offboard_control::StateControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state_ctrl_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StateControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::offboard_control::StateControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::offboard_control::StateControl_<ContainerAllocator>& v)
  {
    s << indent << "state_ctrl_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state_ctrl_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OFFBOARD_CONTROL_MESSAGE_STATECONTROL_H
