// Generated by gencpp from file offboard_control/UpdateBoundOnline.msg
// DO NOT EDIT!


#ifndef OFFBOARD_CONTROL_MESSAGE_UPDATEBOUNDONLINE_H
#define OFFBOARD_CONTROL_MESSAGE_UPDATEBOUNDONLINE_H

#include <ros/service_traits.h>


#include <offboard_control/UpdateBoundOnlineRequest.h>
#include <offboard_control/UpdateBoundOnlineResponse.h>


namespace offboard_control
{

struct UpdateBoundOnline
{

typedef UpdateBoundOnlineRequest Request;
typedef UpdateBoundOnlineResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateBoundOnline
} // namespace offboard_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::offboard_control::UpdateBoundOnline > {
  static const char* value()
  {
    return "b63d0873a52c6e04efd40342ee8fed38";
  }

  static const char* value(const ::offboard_control::UpdateBoundOnline&) { return value(); }
};

template<>
struct DataType< ::offboard_control::UpdateBoundOnline > {
  static const char* value()
  {
    return "offboard_control/UpdateBoundOnline";
  }

  static const char* value(const ::offboard_control::UpdateBoundOnline&) { return value(); }
};


// service_traits::MD5Sum< ::offboard_control::UpdateBoundOnlineRequest> should match
// service_traits::MD5Sum< ::offboard_control::UpdateBoundOnline >
template<>
struct MD5Sum< ::offboard_control::UpdateBoundOnlineRequest>
{
  static const char* value()
  {
    return MD5Sum< ::offboard_control::UpdateBoundOnline >::value();
  }
  static const char* value(const ::offboard_control::UpdateBoundOnlineRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::offboard_control::UpdateBoundOnlineRequest> should match
// service_traits::DataType< ::offboard_control::UpdateBoundOnline >
template<>
struct DataType< ::offboard_control::UpdateBoundOnlineRequest>
{
  static const char* value()
  {
    return DataType< ::offboard_control::UpdateBoundOnline >::value();
  }
  static const char* value(const ::offboard_control::UpdateBoundOnlineRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::offboard_control::UpdateBoundOnlineResponse> should match
// service_traits::MD5Sum< ::offboard_control::UpdateBoundOnline >
template<>
struct MD5Sum< ::offboard_control::UpdateBoundOnlineResponse>
{
  static const char* value()
  {
    return MD5Sum< ::offboard_control::UpdateBoundOnline >::value();
  }
  static const char* value(const ::offboard_control::UpdateBoundOnlineResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::offboard_control::UpdateBoundOnlineResponse> should match
// service_traits::DataType< ::offboard_control::UpdateBoundOnline >
template<>
struct DataType< ::offboard_control::UpdateBoundOnlineResponse>
{
  static const char* value()
  {
    return DataType< ::offboard_control::UpdateBoundOnline >::value();
  }
  static const char* value(const ::offboard_control::UpdateBoundOnlineResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OFFBOARD_CONTROL_MESSAGE_UPDATEBOUNDONLINE_H
