// Generated by gencpp from file offboard_control/UpdateBoundOnlineResponse.msg
// DO NOT EDIT!


#ifndef OFFBOARD_CONTROL_MESSAGE_UPDATEBOUNDONLINERESPONSE_H
#define OFFBOARD_CONTROL_MESSAGE_UPDATEBOUNDONLINERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace offboard_control
{
template <class ContainerAllocator>
struct UpdateBoundOnlineResponse_
{
  typedef UpdateBoundOnlineResponse_<ContainerAllocator> Type;

  UpdateBoundOnlineResponse_()
    : success(false)
    , isBoundUpdate(false)  {
    }
  UpdateBoundOnlineResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , isBoundUpdate(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef uint8_t _isBoundUpdate_type;
  _isBoundUpdate_type isBoundUpdate;





  typedef boost::shared_ptr< ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateBoundOnlineResponse_

typedef ::offboard_control::UpdateBoundOnlineResponse_<std::allocator<void> > UpdateBoundOnlineResponse;

typedef boost::shared_ptr< ::offboard_control::UpdateBoundOnlineResponse > UpdateBoundOnlineResponsePtr;
typedef boost::shared_ptr< ::offboard_control::UpdateBoundOnlineResponse const> UpdateBoundOnlineResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator1> & lhs, const ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.isBoundUpdate == rhs.isBoundUpdate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator1> & lhs, const ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace offboard_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c83de6d27285b4ae782a6260754280b";
  }

  static const char* value(const ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c83de6d27285b4aULL;
  static const uint64_t static_value2 = 0xe782a6260754280bULL;
};

template<class ContainerAllocator>
struct DataType< ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "offboard_control/UpdateBoundOnlineResponse";
  }

  static const char* value(const ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"bool isBoundUpdate\n"
;
  }

  static const char* value(const ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.isBoundUpdate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateBoundOnlineResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::offboard_control::UpdateBoundOnlineResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "isBoundUpdate: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isBoundUpdate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OFFBOARD_CONTROL_MESSAGE_UPDATEBOUNDONLINERESPONSE_H
